### ISSUE TITLE
Render graph using D3 visualisation

### ISSUE THREAD

**Issue by adrianwithah** [justincqz/orbit-db-time-machine#25] opened 2019-10-14 14:34 UTC
- [x] Make a proper page for displaying DAG
- [ ] Render a stunning graph using DAGnodes

**Comment by hannessolo** [comment] 2019-10-14 15:40
The page technically already exists, we just need to make it look nicer

**Comment by hannessolo** [comment] 2019-10-15 11:20
Duplicate of #19

**Comment by hannessolo** [comment] 2019-10-15 11:22
Actually I'll close the other issue instead

**Closed** 2019-10-16 14:41 UTC
Labels: enhancement
